@startuml
!theme crt-green
    [tn3270j]
    package jmacro{
        [cli]
        package commands{
            [base]
            [browser]
            [datax]
            [io]
            [server]
            [terminal]
        }
        [core]
        [installer]
    }
@enduml
