@startuml
!theme crt-green
package jmacro{
    [cli]
    package commands{
        [base]
        [browser]
        [datax]
        [db]
        [io]
        [server]
        [terminal]
    }
    [core]
    [installer]
}
@enduml
