package com.itquasar.multiverse.jmacro.commands.datax.commands.com.enums.visio;

import com.itquasar.multiverse.jmacro.commands.datax.commands.com.enums.COMEnum;
import com.jacob.com.Variant;

/**@
  Commands for data extraction

  {@see <a href="https://docs.microsoft.com/en-us/office/vba/api/visio.visuicmds">https://docs.microsoft.com/en-us/office/vba/api/visio.visuicmds</a>}
*/
public enum VisUICmds implements COMEnum {
    
    /**@ No description provided */
    visCmdABarAutoHeight(1684),    
    /**@ No description provided */
    visCmdABarAutohide(1652),    
    /**@ No description provided */
    visCmdABarHide(1650),    
    /**@ No description provided */
    visCmdABarToggleFloat(1651),    
    /**@ No description provided */
    visCmdAcquireImages(1868),    
    /**@ No description provided */
    visCmdAddConnectPt(1263),    
    /**@ No description provided */
    visCmdAddControlPt(1266),    
    /**@ No description provided */
    visCmdAddDataRecordset(1998),    
    /**@ No description provided */
    visCmdAddMemberToContainer(2173),    
    /**@ No description provided */
    visCmdAddTextShape(1181),    
    /**@ No description provided */
    visCmdAddToAllContainers(2251),    
    /**@ No description provided */
    visCmdAddToNewContainer(2268),    
    /**@ No description provided */
    visCmdAlignBox(1768),    
    /**@ No description provided */
    visCmdAlignObjectBottom(1201),    
    /**@ No description provided */
    visCmdAlignObjectCenter(1197),    
    /**@ No description provided */
    visCmdAlignObjectLeft(1196),    
    /**@ No description provided */
    visCmdAlignObjectMiddle(1200),    
    /**@ No description provided */
    visCmdAlignObjectRight(1198),    
    /**@ No description provided */
    visCmdAlignObjectTop(1199),    
    /**@ No description provided */
    visCmdAllowThemes(2056),    
    /**@ No description provided */
    visCmdApplyDataGraphic(2017),    
    /**@ No description provided */
    visCmdApplyDataGraphicAfterLink(2092),    
    /**@ No description provided */
    visCmdApplyMainTheme(2285),    
    /**@ No description provided */
    visCmdApplyMainThemeToDocument(2296),    
    /**@ No description provided */
    visCmdApplyMainThemeToPage(2289),    
    /**@ No description provided */
    visCmdApplyThemeColors(2188),    
    /**@ No description provided */
    visCmdApplyThemeEffects(2189),    
    /**@ No description provided */
    visCmdApplyThemeToDoc(2048),    
    /**@ No description provided */
    visCmdApplyThemeToNewShapesToggle(2297),    
    /**@ No description provided */
    visCmdApplyThemeToPage(2047),    
    /**@ No description provided */
    visCmdAppMaximize(1864),    
    /**@ No description provided */
    visCmdAppMinimize(1865),    
    /**@ No description provided */
    visCmdAppRestore(1904),    
    /**@ No description provided */
    visCmdAssociateCallout(2287),    
    /**@ No description provided */
    visCmdAutoAlign(2223),    
    /**@ No description provided */
    visCmdAutoAlignAndSpace(2222),    
    /**@ No description provided */
    visCmdAutoConnectToggle(2091),    
    /**@ No description provided */
    visCmdAutoGenerateDataGraphics(2105),    
    /**@ No description provided */
    visCmdAutoSpace(2224),    
    /**@ No description provided */
    visCmdBreakOLELink(1900),    
    /**@ No description provided */
    visCmdBrowseSampleDrawings(1645),    
    /**@ No description provided */
    visCmdBullets(1633),    
    /**@ No description provided */
    visCmdCancelInPlaceEditing(1602),    
    /**@ No description provided */
    visCmdCenterDrawing(1202),    
    /**@ No description provided */
    visCmdCheckCompatibility(2182),    
    /**@ No description provided */
    visCmdCloseInkToolsRibbonTab(2213),    
    /**@ No description provided */
    visCmdCloseWindow(1361),    
    /**@ No description provided */
    visCmdCoauthMerging(2385),    
    /**@ No description provided */
    visCmdCollapseShapesWindow(2269),    
    /**@ No description provided */
    visCmdConnectorEffectCurved(1945),    
    /**@ No description provided */
    visCmdConnectorEffectRightAngle(1943),    
    /**@ No description provided */
    visCmdConnectorEffectStraight(1944),    
    /**@ No description provided */
    visCmdConnPoints(1774),    
    /**@ No description provided */
    visCmdContainerNoHeadingToggle(2315),    
    /**@ No description provided */
    visCmdContainerAutoResizeExpandContract(2349),    
    /**@ No description provided */
    visCmdContainerAutoResizeExpandOnly(2348),    
    /**@ No description provided */
    visCmdContainerAutoResizeOff(2347),    
    /**@ No description provided */
    visCmdCreateEditMaster(1899),    
    /**@ No description provided */
    visCmdCreateNewDrawing(1812),    
    /**@ No description provided */
    visCmdCreateShortcut(1791),    
    /**@ No description provided */
    visCmdCropObject(1192),    
    /**@ No description provided */
    visCmdCropTool(1449),    
    /**@ No description provided */
    visCmdCustomPropertySets(1675),    
    /**@ No description provided */
    visCmdCustProp(1658),    
    /**@ No description provided */
    visCmdCustPropDefine(1695),    
    /**@ No description provided */
    visCmdDataAutoConnect(2098),    
    /**@ No description provided */
    visCmdDataAutoLink(2046),    
    /**@ No description provided */
    visCmdDataAutoLinkWiz(2045),    
    /**@ No description provided */
    visCmdDataColumnSettingsDlg(2043),    
    /**@ No description provided */
    visCmdDataExplorerWindow(2044),    
    /**@ No description provided */
    visCmdDataRecordsetProperties(2072),    
    /**@ No description provided */
    visCmdDataRecordsetSetCommand(2037),    
    /**@ No description provided */
    visCmdDataRecordsetSetPrimaryKey(2038),    
    /**@ No description provided */
    visCmdDataRefresh(2021),    
    /**@ No description provided */
    visCmdDataRefreshAddConflict(2094),    
    /**@ No description provided */
    visCmdDataRefreshConfigDlg(2022),    
    /**@ No description provided */
    visCmdDataRefreshDeleteConflict(2095),    
    /**@ No description provided */
    visCmdDataRefreshDlg(2019),    
    /**@ No description provided */
    visCmdDataRefreshResolveConflict(2103),    
    /**@ No description provided */
    visCmdDataSelectorDlg(2011),    
    /**@ No description provided */
    visCmdDataUnlinkRow(2058),    
    /**@ No description provided */
    visCmdDataUnlinkShape(2057),    
    /**@ No description provided */
    visCmdDecreaseIndent(1093),    
    /**@ No description provided */
    visCmdDecreaseParaSpacing(1095),    
    /**@ No description provided */
    visCmdDelConnectPt(1265),    
    /**@ No description provided */
    visCmdDeleteBackWord(1905),    
    /**@ No description provided */
    visCmdDeleteComment(1920),    
    /**@ No description provided */
    visCmdDeleteConnectors(2199),    
    /**@ No description provided */
    visCmdDeleteDataGraphic(2067),    
    /**@ No description provided */
    visCmdDeleteDataRecordset(1999),    
    /**@ No description provided */
    visCmdDeleteForwardWord(2114),    
    /**@ No description provided */
    visCmdDeleteTheme(2052),    
    /**@ No description provided */
    visCmdDeselectAll(1213),    
    /**@ No description provided */
    visCmdDesignMode(1388),    
    /**@ No description provided */
    visCmdDetectAndRepair(1890),    
    /**@ No description provided */
    visCmdDiagramFlipHorizontal(2229),    
    /**@ No description provided */
    visCmdDiagramFlipVertical(2228),    
    /**@ No description provided */
    visCmdDiagramGallery(1982),    
    /**@ No description provided */
    visCmdDiagramRotateLeft(2227),    
    /**@ No description provided */
    visCmdDiagramRotateRight(2226),    
    /**@ No description provided */
    visCmdDisbandContainer(2204),    
    /**@ No description provided */
    visCmdDistributeBottom(1238),    
    /**@ No description provided */
    visCmdDistributeCenter(1233),    
    /**@ No description provided */
    visCmdDistributeHSpace(1231),    
    /**@ No description provided */
    visCmdDistributeLeft(1232),    
    /**@ No description provided */
    visCmdDistributeMiddle(1237),    
    /**@ No description provided */
    visCmdDistributeRight(1234),    
    /**@ No description provided */
    visCmdDistributeTop(1236),    
    /**@ No description provided */
    visCmdDistributeVSpace(1235),    
    /**@ No description provided */
    visCmdDlgCustomFit(1536),    
    /**@ No description provided */
    visCmdDragDuplicate(1184),    
    /**@ No description provided */
    visCmdDrawFillStyle(1123),    
    /**@ No description provided */
    visCmdDrawGlue(1125),    
    /**@ No description provided */
    visCmdDrawAddGuide(1180),    
    /**@ No description provided */
    visCmdDrawingExplorer(1721),    
    /**@ No description provided */
    visCmdDrawingTools(1946),    
    /**@ No description provided */
    visCmdDrawLineStyle(1122),    
    /**@ No description provided */
    visCmdDrawOval(1183),    
    /**@ No description provided */
    visCmdDrawSnap(1124),    
    /**@ No description provided */
    visCmdDrawRect(1182),    
    /**@ No description provided */
    visCmdDrawRegion(1742),    
    /**@ No description provided */
    visCmdDrawTextStyle(1121),    
    /**@ No description provided */
    visCmdDrawZoom(1126),    
    /**@ No description provided */
    visCmdDRConnectionTool(1226),    
    /**@ No description provided */
    visCmdDRConnectorTool(1225),    
    /**@ No description provided */
    visCmdDRLineTool(1221),    
    /**@ No description provided */
    visCmdDropAndContain(2172),    
    /**@ No description provided */
    visCmdDropAndInsertIntoList(2196),    
    /**@ No description provided */
    visCmdDropCallout(2286),    
    /**@ No description provided */
    visCmdDropManyOnPage(1869),    
    /**@ No description provided */
    visCmdDropManyLinked(2108),    
    /**@ No description provided */
    visCmdDropOnPage(1246),    
    /**@ No description provided */
    visCmdDropOnStencil(1244),    
    /**@ No description provided */
    visCmdDropOnText(1243),    
    /**@ No description provided */
    visCmdDROvalTool(1224),    
    /**@ No description provided */
    visCmdDRPencilTool(1220),    
    /**@ No description provided */
    visCmdDRPointerTool(1219),    
    /**@ No description provided */
    visCmdDRQtrArcTool(1222),    
    /**@ No description provided */
    visCmdDRRectTool(1223),    
    /**@ No description provided */
    visCmdDRRotateTool(1228),    
    /**@ No description provided */
    visCmdDRSplineTool(1311),    
    /**@ No description provided */
    visCmdDRTextTool(1227),    
    /**@ No description provided */
    visCmdDuplicateDataGraphic(2106),    
    /**@ No description provided */
    visCmdDuplicatePage(2383),    
    /**@ No description provided */
    visCmdDuplicateTheme(2050),    
    /**@ No description provided */
    visCmdEditUndoMultiple(1682),    
    /**@ No description provided */
    visCmdDynamicGrid(1765),    
    /**@ No description provided */
    visCmdDynConnReroute(1829),    
    /**@ No description provided */
    visCmdEditConvertObject(1439),    
    /**@ No description provided */
    visCmdEditFind(1043),    
    /**@ No description provided */
    visCmdEditInsertField(1032),    
    /**@ No description provided */
    visCmdEditInsertObject(1031),    
    /**@ No description provided */
    visCmdEditLinks(1030),    
    /**@ No description provided */
    visCmdEditOpenObject(1029),    
    /**@ No description provided */
    visCmdEditPasteLink(1028),    
    /**@ No description provided */
    visCmdEditPasteSpecial(1027),    
    /**@ No description provided */
    visCmdEditRedo(1018),    
    /**@ No description provided */
    visCmdEditRedoMultiple(1683),    
    /**@ No description provided */
    visCmdEditRedoOrRepeat(2295),    
    /**@ No description provided */
    visCmdEditRepeat(1019),    
    /**@ No description provided */
    visCmdEditReplace(1179),    
    /**@ No description provided */
    visCmdEditSelectSpecial(1026),    
    /**@ No description provided */
    visCmdEditTheme(2049),    
    /**@ No description provided */
    visCmdEditThemeColors(2190),    
    /**@ No description provided */
    visCmdEditThemeEffects(2191),    
    /**@ No description provided */
    visCmdEditUndo(1017),    
    /**@ No description provided */
    visCmdEmailRouting(1588),    
    /**@ No description provided */
    visCmdExportDatabaseAddon(1891),    
    /**@ No description provided */
    visCmdFileCheckin(1787),    
    /**@ No description provided */
    visCmdFileCheckout(1788),    
    /**@ No description provided */
    visCmdFileChooseTemplates(1583),    
    /**@ No description provided */
    visCmdFileClose(1003),    
    /**@ No description provided */
    visCmdFileExit(1016),    
    /**@ No description provided */
    visCmdFileImport(1007),    
    /**@ No description provided */
    visCmdFileLastFile1(1012),    
    /**@ No description provided */
    visCmdFileLastFile10(2127),    
    /**@ No description provided */
    visCmdFileLastFile11(2128),    
    /**@ No description provided */
    visCmdFileLastFile12(2129),    
    /**@ No description provided */
    visCmdFileLastFile13(2130),    
    /**@ No description provided */
    visCmdFileLastFile14(2131),    
    /**@ No description provided */
    visCmdFileLastFile15(2132),    
    /**@ No description provided */
    visCmdFileLastFile16(2133),    
    /**@ No description provided */
    visCmdFileLastFile17(2134),    
    /**@ No description provided */
    visCmdFileLastFile18(2136),    
    /**@ No description provided */
    visCmdFileLastFile19(1012),    
    /**@ No description provided */
    visCmdFileLastFile2(1013),    
    /**@ No description provided */
    visCmdFileLastFile20(2137),    
    /**@ No description provided */
    visCmdFileLastFile3(1014),    
    /**@ No description provided */
    visCmdFileLastFile4(1015),    
    /**@ No description provided */
    visCmdFileLastFile5(1561),    
    /**@ No description provided */
    visCmdFileLastFile6(1569),    
    /**@ No description provided */
    visCmdFileLastFile7(1570),    
    /**@ No description provided */
    visCmdFileLastFile8(1571),    
    /**@ No description provided */
    visCmdFileLastFile9(1572),    
    /**@ No description provided */
    visCmdFileNew(1001),    
    /**@ No description provided */
    visCmdFileNewBlankDrawing(1579),    
    /**@ No description provided */
    visCmdFileNewBlankDrawingMetric(1671),    
    /**@ No description provided */
    visCmdFileNewBlankDrawingUS(1672),    
    /**@ No description provided */
    visCmdFileNewBlankStencil(1582),    
    /**@ No description provided */
    visCmdFileNewBlankStencilMetric(1673),    
    /**@ No description provided */
    visCmdFileNewBlankStencilUS(1674),    
    /**@ No description provided */
    visCmdFileNewStencilDlg(1580),    
    /**@ No description provided */
    visCmdFileOpen(1002),    
    /**@ No description provided */
    visCmdFileOpenStencil(1442),    
    /**@ No description provided */
    visCmdFilePrint(1010),    
    /**@ No description provided */
    visCmdFileSave(1004),    
    /**@ No description provided */
    visCmdFileSaveAs(1005),    
    /**@ No description provided */
    visCmdFileSaveAsDrawing(2306),    
    /**@ No description provided */
    visCmdFileSaveAsDrawingPreviousFileFormat(2298),    
    /**@ No description provided */
    visCmdFileSaveAsDWG(2305),    
    /**@ No description provided */
    visCmdFileSaveAsEMF(2302),    
    /**@ No description provided */
    visCmdFileSaveAsJPG(2301),    
    /**@ No description provided */
    visCmdFileSaveAsMacroDrawing(2311),    
    /**@ No description provided */
    visCmdFileSaveAsPNG(2300),    
    /**@ No description provided */
    visCmdFileSaveAsSVG(2303),    
    /**@ No description provided */
    visCmdFileSaveAsTemplate(2299),    
    /**@ No description provided */
    visCmdFileSaveAsWebPage(1785),    
    /**@ No description provided */
    visCmdFileSaveWorkspace(1006),    
    /**@ No description provided */
    visCmdFileSummaryInfoDlg(1009),    
    /**@ No description provided */
    visCmdFileUndoCheckout(2109),    
    /**@ No description provided */
    visCmdFirstTile(1515),    
    /**@ No description provided */
    visCmdFitContainerToContents(2195),    
    /**@ No description provided */
    visCmdFitCurve(1538),    
    /**@ No description provided */
    visCmdFormatAllTextProps(1642),    
    /**@ No description provided */
    visCmdFormatBehavior(1071),    
    /**@ No description provided */
    visCmdFormatBlock(1070),    
    /**@ No description provided */
    visCmdFormatCorners(1334),    
    /**@ No description provided */
    visCmdFormatCustPropDef(1687),    
    /**@ No description provided */
    visCmdFormatCustPropEdit(1312),    
    /**@ No description provided */
    visCmdFormatDefineStyles(1064),    
    /**@ No description provided */
    visCmdFormatDoubleClick(1118),    
    /**@ No description provided */
    visCmdFormatFill(1066),    
    /**@ No description provided */
    visCmdFormatInkDlg(1955),    
    /**@ No description provided */
    visCmdFormatLine(1065),    
    /**@ No description provided */
    visCmdFormatPainter(1271),    
    /**@ No description provided */
    visCmdFormatParagraph(1068),    
    /**@ No description provided */
    visCmdFormatPictureAutobalance(2205),    
    /**@ No description provided */
    visCmdFormatPictureCompressionDlg(2212),    
    /**@ No description provided */
    visCmdFormatProtection(1072),    
    /**@ No description provided */
    visCmdFormatShadow(1333),    
    /**@ No description provided */
    visCmdFormatSpecial(1073),    
    /**@ No description provided */
    visCmdFormatStyle(1063),    
    /**@ No description provided */
    visCmdFormatTabs(1069),    
    /**@ No description provided */
    visCmdFormatText(1067),    
    /**@ No description provided */
    visCmdFullScreenMode(1492),    
    /**@ No description provided */
    visCmdGoToPageToolbar(1635),    
    /**@ No description provided */
    visCmdGrid(1767),    
    /**@ No description provided */
    visCmdGuides(1771),    
    /**@ No description provided */
    visCmdHeaderFooter(1720),    
    /**@ No description provided */
    visCmdHelpAboutVisio(1100),    
    /**@ No description provided */
    visCmdHelpContents(1092),    
    /**@ No description provided */
    visCmdHelpMode(1386),    
    /**@ No description provided */
    visCmdHelpSearch(1809),    
    /**@ No description provided */
    visCmdHelpShapeBasics(1822),    
    /**@ No description provided */
    visCmdHelpTemplates(1586),    
    /**@ No description provided */
    visCmdHideAllToolbars(1726),    
    /**@ No description provided */
    visCmdHideDocumentStencil(1689),    
    /**@ No description provided */
    visCmdHideMoreShapes(2291),    
    /**@ No description provided */
    visCmdHyperlinkHier(1611),    
    /**@ No description provided */
    visCmdHyperlinkList(1719),    
    /**@ No description provided */
    visCmdIconBucketTool(1543),    
    /**@ No description provided */
    visCmdIconLassoTool(1544),    
    /**@ No description provided */
    visCmdIconLeftColor(1143),    
    /**@ No description provided */
    visCmdIconPencilTool(1145),    
    /**@ No description provided */
    visCmdIconRightTool(1144),    
    /**@ No description provided */
    visCmdIconSelectNet(1545),    
    /**@ No description provided */
    visCmdIgnoreValidationIssue(2254),    
    /**@ No description provided */
    visCmdIgnoreValidationRule(2256),    
    /**@ No description provided */
    visCmdImageProperties(1887),    
    /**@ No description provided */
    visCmdImagePropertiesDlg(1883),    
    /**@ No description provided */
    visCmdIncreaseIndent(1094),    
    /**@ No description provided */
    visCmdIncreaseParaSpacing(1096),    
    /**@ No description provided */
    visCmdINETAddToFavorites(1506),    
    /**@ No description provided */
    visCmdINETCopyHyperlink(1610),    
    /**@ No description provided */
    visCmdINETDeleteHlink(1609),    
    /**@ No description provided */
    visCmdINETDiagrammingResources(1606),    
    /**@ No description provided */
    visCmdINETEditHyperlink(1619),    
    /**@ No description provided */
    visCmdINETGoBack(1599),    
    /**@ No description provided */
    visCmdINETGoForward(1598),    
    /**@ No description provided */
    visCmdINETKnowledgeBase(1605),    
    /**@ No description provided */
    visCmdINETOpenHLink(1607),    
    /**@ No description provided */
    visCmdINETOpenHLinkNewWnd(1608),    
    /**@ No description provided */
    visCmdINETPasteAsHyperlink(1620),    
    /**@ No description provided */
    visCmdINETUserSearchPage(1595),    
    /**@ No description provided */
    visCmdINETVisioHomePage(1596),    
    /**@ No description provided */
    visCmdINETVisioOnTheWeb(1831),    
    /**@ No description provided */
    visCmdINETVisioSolutionsLibrary(1604),    
    /**@ No description provided */
    visCmdInkEraser(1970),    
    /**@ No description provided */
    visCmdInkReviewPen(1971),    
    /**@ No description provided */
    visCmdInkStockPen0(1973),    
    /**@ No description provided */
    visCmdInkStockPen1(1974),    
    /**@ No description provided */
    visCmdInkTool(1661),    
    /**@ No description provided */
    visCmdInsertAutoCADAddOn(1521),    
    /**@ No description provided */
    visCmdInsertCheckBoxControl(2150),    
    /**@ No description provided */
    visCmdInsertClipArt(1497),    
    /**@ No description provided */
    visCmdInsertClipArtDlg(2345),    
    /**@ No description provided */
    visCmdInsertComboBoxControl(2152),    
    /**@ No description provided */
    visCmdInsertComment(1501),    
    /**@ No description provided */
    visCmdInsertControlDlg(1522),    
    /**@ No description provided */
    visCmdInsertDataMap(1282),    
    /**@ No description provided */
    visCmdInserTextBoxControl(2145),    
    /**@ No description provided */
    visCmdInsertHyperLink(1585),    
    /**@ No description provided */
    visCmdInsertImageControl(2148),    
    /**@ No description provided */
    visCmdInsertLabelControl(2144),    
    /**@ No description provided */
    visCmdInsertLegendHorizontal(2331),    
    /**@ No description provided */
    visCmdInsertLegendVertical1(2335),    
    /**@ No description provided */
    visCmdInsertListBoxControl(2153),    
    /**@ No description provided */
    visCmdInsertMemberIntoList(2174),    
    /**@ No description provided */
    visCmdInsertMicrosoftGraph(1499),    
    /**@ No description provided */
    visCmdInsertNewBackgroundPage(2165),    
    /**@ No description provided */
    visCmdInsertPageTab(2202),    
    /**@ No description provided */
    visCmdInsertPushButtonControl(2147),    
    /**@ No description provided */
    visCmdInsertRadioButtonControl(2151),    
    /**@ No description provided */
    visCmdInsertScrollBarControl(2149),    
    /**@ No description provided */
    visCmdInsertSpinControl(2146),    
    /**@ No description provided */
    visCmdInsertTextBox(2006),    
    /**@ No description provided */
    visCmdInsertToggleButtonControl(2154),    
    /**@ No description provided */
    visCmdInsertVertTextBox(2007),    
    /**@ No description provided */
    visCmdInsertWordArt(1498),    
    /**@ No description provided */
    visCmdIntersect(1453),    
    /**@ No description provided */
    visCmdJoin(1533),    
    /**@ No description provided */
    visCmdLanguagePreferencesDlg(2363),    
    /**@ No description provided */
    visCmdLast(65535),    
    /**@ No description provided */
    visCmdLastTile(1516),    
    /**@ No description provided */
    visCmdLayerDlg(1446),    
    /**@ No description provided */
    visCmdLayerSetupDlg(1448),    
    /**@ No description provided */
    visCmdLayoutDynamic(1493),    
    /**@ No description provided */
    visCmdLinkRowToShape(1997),    
    /**@ No description provided */
    visCmdListInsertAfter(2271),    
    /**@ No description provided */
    visCmdListInsertBefore(2270),    
    /**@ No description provided */
    visCmdLockContainer(2220),    
    /**@ No description provided */
    visCmdMasterExplorer(1916),    
    /**@ No description provided */
    visCmdMasterSetup(1343),    
    /**@ No description provided */
    visCmdMDIMaximize(1901),    
    /**@ No description provided */
    visCmdMDIMinimize(1902),    
    /**@ No description provided */
    visCmdMDIRestore(1903),    
    /**@ No description provided */
    visCmdMinimizeRibbonToggle(2232),    
    /**@ No description provided */
    visCmdModConnectPt(1264),    
    /**@ No description provided */
    visCmdModControlPt(1267),    
    /**@ No description provided */
    visCmdMovConnectPt(1269),    
    /**@ No description provided */
    visCmdMove1D(1186),    
    /**@ No description provided */
    visCmdMove2D(1187),    
    /**@ No description provided */
    visCmdMoveComment(1502),    
    /**@ No description provided */
    visCmdMoveObject(1185),    
    /**@ No description provided */
    visCmdMsoAutoCorrect(1872),    
    /**@ No description provided */
    visCmdMsoAutoCorrectDlg(1866),    
    /**@ No description provided */
    visCmdMsoAutoFormat(1873),    
    /**@ No description provided */
    visCmdMsoCustomItem(1896),    
    /**@ No description provided */
    visCmdMSOInsertEquation(1646),    
    /**@ No description provided */
    visCmdMSOInsertSymbol(1504),    
    /**@ No description provided */
    visCmdMSOInsertSymbolDlg(1505),    
    /**@ No description provided */
    visCmdMsoMediaGallery(1885),    
    /**@ No description provided */
    visCmdMultipleFileImport(2201),    
    /**@ No description provided */
    visCmdNewDefDocBlankDrawing(1906),    
    /**@ No description provided */
    visCmdNewForegroundPage(2361),    
    /**@ No description provided */
    visCmdNewFromExisting(1897),    
    /**@ No description provided */
    visCmdNewThemeColors(2065),    
    /**@ No description provided */
    visCmdNewThemeEffects(2064),    
    /**@ No description provided */
    visCmdNextCommentMarkup(2180),    
    /**@ No description provided */
    visCmdNextMarkup(1914),    
    /**@ No description provided */
    visCmdNextTile(1514),    
    /**@ No description provided */
    visCmdNextWindow(1886),    
    /**@ No description provided */
    visCmdObjectAddToGroup(1053),    
    /**@ No description provided */
    visCmdObjectAlignObjects(1049),    
    /**@ No description provided */
    visCmdObjectBringForward(1045),    
    /**@ No description provided */
    visCmdObjectBringToFront(1046),    
    /**@ No description provided */
    visCmdObjectCombine(1061),    
    /**@ No description provided */
    visCmdObjectConnectObjects(1050),    
    /**@ No description provided */
    visCmdObjectConvertToGroup(1055),    
    /**@ No description provided */
    visCmdObjectDistributeDlg(1230),    
    /**@ No description provided */
    visCmdObjectFlipHorizontal(1058),    
    /**@ No description provided */
    visCmdObjectFlipVertical(1057),    
    /**@ No description provided */
    visCmdObjectFragment(1062),    
    /**@ No description provided */
    visCmdObjectGroup(1051),    
    /**@ No description provided */
    visCmdObjectHelp(1428),    
    /**@ No description provided */
    visCmdObjectInfoDlg(1425),    
    /**@ No description provided */
    visCmdObjectRemoveFromGroup(1054),    
    /**@ No description provided */
    visCmdObjectReverse(1059),    
    /**@ No description provided */
    visCmdObjectRotate90(1056),    
    /**@ No description provided */
    visCmdObjectSendBackward(1047),    
    /**@ No description provided */
    visCmdObjectSendToBack(1048),    
    /**@ No description provided */
    visCmdObjectSwapEnds(1870),    
    /**@ No description provided */
    visCmdObjectUngroup(1052),    
    /**@ No description provided */
    visCmdObjectUnion(1060),    
    /**@ No description provided */
    visCmdOfficeCenterOptions(2141),    
    /**@ No description provided */
    visCmdOffsetDlg(1387),    
    /**@ No description provided */
    visCmdOfficeDiagnostics(1890),    
    /**@ No description provided */
    visCmdOpenActiveObject(1601),    
    /**@ No description provided */
    visCmdOpenCommentForEdit(1503),    
    /**@ No description provided */
    visCmdOpenInVisio(1491),    
    /**@ No description provided */
    visCmdOptionsColorPaletteDlg(1082),    
    /**@ No description provided */
    visCmdOptionsDeletePages(1079),    
    /**@ No description provided */
    visCmdOptionsEditBackground(1075),    
    /**@ No description provided */
    visCmdOptionsEditDrawing(1074),    
    /**@ No description provided */
    visCmdOptionsGoToDrawing(1077),    
    /**@ No description provided */
    visCmdOptionsNewPage(1078),    
    /**@ No description provided */
    visCmdOptionsPageSetup(1076),    
    /**@ No description provided */
    visCmdOptionsPreferences(1081),    
    /**@ No description provided */
    visCmdOptionsProtectDocument(1083),    
    /**@ No description provided */
    visCmdOptionsReorderPages(1080),    
    /**@ No description provided */
    visCmdOptionsSnapGlueSetup(1084),    
    /**@ No description provided */
    visCmdPageAutoSizeToggle(2333),    
    /**@ No description provided */
    visCmdPageMeasureUnitsDlg(1274),    
    /**@ No description provided */
    visCmdPageSizeDlg(2176),    
    /**@ No description provided */
    visCmdPageSizeToFitDrawing(2332),    
    /**@ No description provided */
    visCmdPagesList(1654),    
    /**@ No description provided */
    visCmdPanObject(1193),    
    /**@ No description provided */
    visCmdPanZoom(1653),    
    /**@ No description provided */
    visCmdPasteShortcut(1790),    
    /**@ No description provided */
    visCmdPasteToLocation(2221),    
    /**@ No description provided */
    visCmdPauseRecordingMacro(1778),    
    /**@ No description provided */
    visCmdPreviousCommentMarkup(2179),    
    /**@ No description provided */
    visCmdPreviousMarkup(1915),    
    /**@ No description provided */
    visCmdPreviousTile(1513),    
    /**@ No description provided */
    visCmdPrintPage(1443),    
    /**@ No description provided */
    visCmdPrintPreview(1490),    
    /**@ No description provided */
    visCmdProgRefHelp(1584),    
    /**@ No description provided */
    visCmdPublishToProcessRepository(2294),    
    /**@ No description provided */
    visCmdPublishToVisioServices(2293),    
    /**@ No description provided */
    visCmdRecalcObjectWH(1146),    
    /**@ No description provided */
    visCmdRecordNewMacro(1775),    
    /**@ No description provided */
    visCmdReinstateValidationIssue(2255),    
    /**@ No description provided */
    visCmdRelayoutShapes(2068),    
    /**@ No description provided */
    visCmdRemoveDataGraphicFromSel(2107),    
    /**@ No description provided */
    visCmdRemoveFromAllContainers(2252),    
    /**@ No description provided */
    visCmdRemoveMemberFromContainer(2175),    
    /**@ No description provided */
    visCmdRemoveMemberFromList(2346),    
    /**@ No description provided */
    visCmdRemoveThemeFromSel(2119),    
    /**@ No description provided */
    visCmdRemoveVBAFromActiveDoc(1590),    
    /**@ No description provided */
    visCmdReorderList(2197),    
    /**@ No description provided */
    visCmdReplaceShape(2051),    
    /**@ No description provided */
    visCmdRHI(2009),    
    /**@ No description provided */
    visCmdRHIDlg(2010),    
    /**@ No description provided */
    visCmdReOrderPage(1795),    
    /**@ No description provided */
    visCmdResearchLookUp(1967),    
    /**@ No description provided */
    visCmdResearchThesaurus(2178),    
    /**@ No description provided */
    visCmdResearchTranslate(1968),    
    /**@ No description provided */
    visCmdResumeRecordingMacro(1779),    
    /**@ No description provided */
    visCmdReviewerVisibilityAll(1836),    
    /**@ No description provided */
    visCmdReviewerVisibilityNone(1919),    
    /**@ No description provided */
    visCmdRightDragCancel(1881),    
    /**@ No description provided */
    visCmdRightDragCopy(1879),    
    /**@ No description provided */
    visCmdRightDragLink(1880),    
    /**@ No description provided */
    visCmdRightDragMove(1878),    
    /**@ No description provided */
    visCmdRotate90Clockwise(1494),    
    /**@ No description provided */
    visCmdRotateObject(1190),    
    /**@ No description provided */
    visCmdRulerGridDlg(1318),    
    /**@ No description provided */
    visCmdRulSub(1766),    
    /**@ No description provided */
    visCmdRunAddOnDlg(1484),    
    /**@ No description provided */
    visCmdRunAddonMenu(1090),    
    /**@ No description provided */
    visCmdSaveAsFixedFormatDlg(2117),    
    /**@ No description provided */
    visCmdSaveForAutoRecover(1857),    
    /**@ No description provided */
    visCmdSelectContainerMembers(2219),    
    /**@ No description provided */
    visCmdSelectionModeExtend(1909),    
    /**@ No description provided */
    visCmdSelectionModeLasso(1908),    
    /**@ No description provided */
    visCmdSelectionModeRect(1907),    
    /**@ No description provided */
    visCmdSendAsMail(1292),    
    /**@ No description provided */
    visCmdSetAddMarkup(1744),    
    /**@ No description provided */
    visCmdSetCharColor(1404),    
    /**@ No description provided */
    visCmdSetCharSizeDown(1406),    
    /**@ No description provided */
    visCmdSetCharSizeUp(1405),    
    /**@ No description provided */
    visCmdSetContainerProperties(2181),    
    /**@ No description provided */
    visCmdSetDynConnAppearanceCurved(1895),    
    /**@ No description provided */
    visCmdSetDynConnAppearanceDefault(1893),    
    /**@ No description provided */
    visCmdSetDynConnAppearanceStraight(1894),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_2pt(1713),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_3pt(1714),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_4pt(1715),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_5pt(1716),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_6pt(1717),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_Arc(1709),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_Gap(1710),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_Page(1708),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_Square(1711),    
    /**@ No description provided */
    visCmdSetDynConnLineJumpStyle_Triangle(1712),    
    /**@ No description provided */
    visCmdSetDynConnRerouteAsNeeded(1697),    
    /**@ No description provided */
    visCmdSetDynConnRerouteFreely(1696),    
    /**@ No description provided */
    visCmdSetDynConnRerouteNever(1698),    
    /**@ No description provided */
    visCmdSetDynConnRerouteOnCrossover(1837),    
    /**@ No description provided */
    visCmdSetDynConnRoutingStyle(1700),    
    /**@ No description provided */
    visCmdSetFillColor(1385),    
    /**@ No description provided */
    visCmdSetFillPattern(1399),    
    /**@ No description provided */
    visCmdSetFillShadow(1379),    
    /**@ No description provided */
    visCmdSetHeaderFooter(1858),    
    /**@ No description provided */
    visCmdSetIndexInStencil(1871),    
    /**@ No description provided */
    visCmdSetLanguageDlg(1888),    
    /**@ No description provided */
    visCmdSetLineColor(1359),    
    /**@ No description provided */
    visCmdSetLineCornerStyle(1358),    
    /**@ No description provided */
    visCmdSetLineEnds(1357),    
    /**@ No description provided */
    visCmdSetLinePattern(1356),    
    /**@ No description provided */
    visCmdSetLineWeight(1355),    
    /**@ No description provided */
    visCmdSetPageLineJumpCode_D(1703),    
    /**@ No description provided */
    visCmdSetPageLineJumpCode_Horz(1705),    
    /**@ No description provided */
    visCmdSetPageLineJumpCode_Last(1707),    
    /**@ No description provided */
    visCmdSetPageLineJumpCode_None(1704),    
    /**@ No description provided */
    visCmdSetPageLineJumpCode_Vert(1706),    
    /**@ No description provided */
    visCmdSetPageOrientation(2170),    
    /**@ No description provided */
    visCmdSetPagePlow(1699),    
    /**@ No description provided */
    visCmdSetPageSize(2171),    
    /**@ No description provided */
    visCmdSetThemeBehavior(2382),    
    /**@ No description provided */
    visCmdShapeActions(1309),    
    /**@ No description provided */
    visCmdShapeComment(1686),    
    /**@ No description provided */
    visCmdShapeCommentDelete(1688),    
    /**@ No description provided */
    visCmdShapeCommentDlg(1685),    
    /**@ No description provided */
    visCmdShapeExplorer(1389),    
    /**@ No description provided */
    visCmdShapeGalleryAddOn(1867),    
    /**@ No description provided */
    visCmdShapeGeo(1769),    
    /**@ No description provided */
    visCmdShapeHand(1772),    
    /**@ No description provided */
    visCmdShapeIntersect(1830),    
    /**@ No description provided */
    visCmdShapeLayerToolbar(1634),    
    /**@ No description provided */
    visCmdShapeSearchWindowToggle(2344),    
    /**@ No description provided */
    visCmdShapeStudioAddOn(1985),    
    /**@ No description provided */
    visCmdShapesWindow(1669),    
    /**@ No description provided */
    visCmdShapeTransparency(1875),    
    /**@ No description provided */
    visCmdShapeTransparencyDlg(1874),    
    /**@ No description provided */
    visCmdShapeVert(1773),    
    /**@ No description provided */
    visCmdShowIgnoredIssuesToggle(2258),    
    /**@ No description provided */
    visCmdShowLineJumpsToggle(2231),    
    /**@ No description provided */
    visCmdShowShapeSheetDocument(2169),    
    /**@ No description provided */
    visCmdShowShapeSheetPage(2168),    
    /**@ No description provided */
    visCmdShowShapeSheetShape(2167),    
    /**@ No description provided */
    visCmdSize1D(1188),    
    /**@ No description provided */
    visCmdSize2D(1189),    
    /**@ No description provided */
    visCmdSizeObjects(1925),    
    /**@ No description provided */
    visCmdSizePos(1670),    
    /**@ No description provided */
    visCmdSizeTextBlock(1194),    
    /**@ No description provided */
    visCmdSmartAlign(2223),    
    /**@ No description provided */
    visCmdSmartAlignAndSpace(2222),    
    /**@ No description provided */
    visCmdSmartSpace(2224),    
    /**@ No description provided */
    visCmdSpaceShapesAvoidPageBreaksToggle(2340),    
    /**@ No description provided */
    visCmdSpellingChange(1889),    
    /**@ No description provided */
    visCmdSpellingOptionsDlg(2042),    
    /**@ No description provided */
    visCmdSSWindowAddSection(1384),    
    /**@ No description provided */
    visCmdSSWindowChangeRowType(1383),    
    /**@ No description provided */
    visCmdSSWindowCollapse(1250),    
    /**@ No description provided */
    visCmdSSWindowDeselect(1253),    
    /**@ No description provided */
    visCmdSSWindowExpand(1251),    
    /**@ No description provided */
    visCmdSSWindowPasteFunction(1382),    
    /**@ No description provided */
    visCmdSSWindowPasteName(1381),    
    /**@ No description provided */
    visCmdSSWindowSelect(1252),    
    /**@ No description provided */
    visCmdSSWindowShowSection(1380),    
    /**@ No description provided */
    visCmdSSWindowShowTraceWindow(1781),    
    /**@ No description provided */
    visCmdStampTool(1424),    
    /**@ No description provided */
    visCmdStartRecordingMacro(1776),    
    /**@ No description provided */
    visCmdStenActivate(1458),    
    /**@ No description provided */
    visCmdStenAutoArrange(1483),    
    /**@ No description provided */
    visCmdStenCleanup(1106),    
    /**@ No description provided */
    visCmdStenClose(1452),    
    /**@ No description provided */
    visCmdStenDrawingExplorer(1796),    
    /**@ No description provided */
    visCmdStenEditDrawing(1102),    
    /**@ No description provided */
    visCmdStenEditIcon(1101),    
    /**@ No description provided */
    visCmdStenEditOff(1681),    
    /**@ No description provided */
    visCmdStenEditOn(1680),    
    /**@ No description provided */
    visCmdStenEditToggle(1679),    
    /**@ No description provided */
    visCmdStenIconAndDetail(1892),    
    /**@ No description provided */
    visCmdStenIconAndName(1480),    
    /**@ No description provided */
    visCmdStenIconOnly(1481),    
    /**@ No description provided */
    visCmdStenImageMaster(1105),    
    /**@ No description provided */
    visCmdStenNameMaster(1103),    
    /**@ No description provided */
    visCmdStenNameOnly(1482),    
    /**@ No description provided */
    visCmdStenNamesUnderIcons(2005),    
    /**@ No description provided */
    visCmdStenNewMaster(1104),    
    /**@ No description provided */
    visCmdStenProperties(1678),    
    /**@ No description provided */
    visCmdStenSave(1676),    
    /**@ No description provided */
    visCmdStenSaveAs(1677),    
    /**@ No description provided */
    visCmdStopIgnoringValidationRule(2257),    
    /**@ No description provided */
    visCmdStopRecordingMacro(1777),    
    /**@ No description provided */
    visCmdSubtract(1454),    
    /**@ No description provided */
    visCmdSWAccept(1140),    
    /**@ No description provided */
    visCmdSWAddSectionDlg(1116),    
    /**@ No description provided */
    visCmdSWCancel(1139),    
    /**@ No description provided */
    visCmdSWChangeRowTypeDlg(1114),    
    /**@ No description provided */
    visCmdSWDeleteRow(1115),    
    /**@ No description provided */
    visCmdSWDeleteSection(1117),    
    /**@ No description provided */
    visCmdSWExpandRow(1718),    
    /**@ No description provided */
    visCmdSWFormula(1141),    
    /**@ No description provided */
    visCmdSWInsertRow(1112),    
    /**@ No description provided */
    visCmdSWInsertRowAfter(1113),    
    /**@ No description provided */
    visCmdSWPasteFunctionDlg(1111),    
    /**@ No description provided */
    visCmdSWPasteNameDlg(1110),    
    /**@ No description provided */
    visCmdSWShapeActionDlg(1444),    
    /**@ No description provided */
    visCmdSWShowFormulas(1108),    
    /**@ No description provided */
    visCmdSWShowSectionsDlg(1109),    
    /**@ No description provided */
    visCmdSWShowToggle(1142),    
    /**@ No description provided */
    visCmdSWShowValues(1107),    
    /**@ No description provided */
    visCmdTaskPane(1896),    
    /**@ No description provided */
    visCmdTaskPaneDataGraphic(2024),    
    /**@ No description provided */
    visCmdTaskPaneDocumentManagement(1972),    
    /**@ No description provided */
    visCmdTaskPaneResearch(1969),    
    /**@ No description provided */
    visCmdTaskPaneReviewer(1939),    
    /**@ No description provided */
    visCmdTaskTogglePreviewSize(2053),    
    /**@ No description provided */
    visCmdTextAllCaps(1862),    
    /**@ No description provided */
    visCmdTextBlockTool(1451),    
    /**@ No description provided */
    visCmdTextBold(1131),    
    /**@ No description provided */
    visCmdTextDoubleStrikeThrough(1951),    
    /**@ No description provided */
    visCmdTextDoubleULine(1863),    
    /**@ No description provided */
    visCmdTextEditRuler(1810),    
    /**@ No description provided */
    visCmdTextEditState(1214),    
    /**@ No description provided */
    visCmdTextFont(1129),    
    /**@ No description provided */
    visCmdTextHAlignCenter(1408),    
    /**@ No description provided */
    visCmdTextHAlignDistribute(1952),    
    /**@ No description provided */
    visCmdTextHAlignJustify(1412),    
    /**@ No description provided */
    visCmdTextHAlignLeft(1407),    
    /**@ No description provided */
    visCmdTextHAlignRight(1409),    
    /**@ No description provided */
    visCmdTextItalic(1132),    
    /**@ No description provided */
    visCmdTextRotate90(1098),    
    /**@ No description provided */
    visCmdTextSize(1130),    
    /**@ No description provided */
    visCmdTextSmallCaps(1133),    
    /**@ No description provided */
    visCmdTextStrikeThrough(1741),    
    /**@ No description provided */
    visCmdTextStyle(1128),    
    /**@ No description provided */
    visCmdTextSubscript(1135),    
    /**@ No description provided */
    visCmdTextSuperScript(1134),    
    /**@ No description provided */
    visCmdTextULine(1136),    
    /**@ No description provided */
    visCmdTextVAlignBottom(1422),    
    /**@ No description provided */
    visCmdTextVAlignMiddle(1414),    
    /**@ No description provided */
    visCmdTextVAlignTop(1413),    
    /**@ No description provided */
    visCmdToggleDocumentStencil(1690),    
    /**@ No description provided */
    visCmdToolbarsDlg(1500),    
    /**@ No description provided */
    visCmdToolsArrayShapesAddOn(1354),    
    /**@ No description provided */
    visCmdToolsInventory(1335),    
    /**@ No description provided */
    visCmdToolsLayoutShapesDlg(1574),    
    /**@ No description provided */
    visCmdToolsMacroDlg(1577),    
    /**@ No description provided */
    visCmdToolSnapLines(1807),    
    /**@ No description provided */
    visCmdToolsRunVBE(1576),    
    /**@ No description provided */
    visCmdToolsSpelling(1270),    
    /**@ No description provided */
    visCmdTranslateOptions(2352),    
    /**@ No description provided */
    visCmdTrim(1534),    
    /**@ No description provided */
    visCmdTrustCenterDlg(2104),    
    /**@ No description provided */
    visCmdTurnToNextPage(1148),    
    /**@ No description provided */
    visCmdTurnToPrevPage(1147),    
    /**@ No description provided */
    visCmdUFEditClear(1023),    
    /**@ No description provided */
    visCmdUFEditCopy(1021),    
    /**@ No description provided */
    visCmdUFEditCut(1020),    
    /**@ No description provided */
    visCmdUFEditDuplicate(1024),    
    /**@ No description provided */
    visCmdUFEditPaste(1022),    
    /**@ No description provided */
    visCmdUFEditSelectAll(1025),    
    /**@ No description provided */
    visCmdUpgradeThemeModel(2384),    
    /**@ No description provided */
    visCmdUpdateColumnsInLinkedShapes(2061),    
    /**@ No description provided */
    visCmdUpdateContentCache(1241),    
    /**@ No description provided */
    visCmdValidateDiagram(2253),    
    /**@ No description provided */
    visCmdValidationIssueNavigateToShape(2236),    
    /**@ No description provided */
    visCmdValidationIssuesArrangeByCategory(2279),    
    /**@ No description provided */
    visCmdValidationIssuesArrangeByIgnored(2281),    
    /**@ No description provided */
    visCmdValidationIssuesArrangeByPage(2280),    
    /**@ No description provided */
    visCmdValidationIssuesArrangeByRule(2278),    
    /**@ No description provided */
    visCmdValidationIssuesArrangeOriginalOrder(2282),    
    /**@ No description provided */
    visCmdValidationIssuesWindowToggle(2263),    
    /**@ No description provided */
    visCmdView100(1035),    
    /**@ No description provided */
    visCmdView150(1036),    
    /**@ No description provided */
    visCmdView200(1037),    
    /**@ No description provided */
    visCmdView400(1280),    
    /**@ No description provided */
    visCmdView50(1279),    
    /**@ No description provided */
    visCmdView75(1034),    
    /**@ No description provided */
    visCmdViewConnections(1042),    
    /**@ No description provided */
    visCmdViewCustom(1038),    
    /**@ No description provided */
    visCmdViewDirectionToggle(2012),    
    /**@ No description provided */
    visCmdViewFitInWindow(1033),    
    /**@ No description provided */
    visCmdViewGrid(1040),    
    /**@ No description provided */
    visCmdViewGuides(1041),    
    /**@ No description provided */
    visCmdViewLeftToRight(2013),    
    /**@ No description provided */
    visCmdViewPageBreaks(1509),    
    /**@ No description provided */
    visCmdViewRightToLeft(2014),    
    /**@ No description provided */
    visCmdViewRulers(1039),    
    /**@ No description provided */
    visCmdViewStatusBar(1044),    
    /**@ No description provided */
    visCmdWindowCascadeAll(1086),    
    /**@ No description provided */
    visCmdWindowNewWindow(1085),    
    /**@ No description provided */
    visCmdWindowShowDrawPage(1091),    
    /**@ No description provided */
    visCmdWindowShowMasterObjects(1089),    
    /**@ No description provided */
    visCmdWindowShowShapeSheet(1088),    
    /**@ No description provided */
    visCmdWindowTileAll(1087),    
    /**@ No description provided */
    visCmdZoomArea(1218),    
    /**@ No description provided */
    visCmdZoomIn(1216),    
    /**@ No description provided */
    visCmdZoomInIgnoreSel(1917),    
    /**@ No description provided */
    visCmdZoomLast(1495),    
    /**@ No description provided */
    visCmdZoomOut(1217),    
    /**@ No description provided */
    visCmdZoomOutIgnoreSel(1918),    
    /**@ No description provided */
    visCmdZoomPageWidth(1496),    
    /**@ No description provided */
    visCmdZoomPt(1215),    
    /**@ No description provided */
    visCmdZoomSingleTile(1512);

    private final long value;

    VisUICmds(long value) {
        this.value = value;
    }

    @Override
    public Variant toVariant() {
        return new Variant(this.value);
    }

    @Override
    public long getValue() {
        return this.value;
    }
}
